version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: fuflofer/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: fuflofer/foodgram_frontend
    env_file: .env
    volumes:
      - static:/static

  nginx:
    image: fuflofer/foodgram_nginx
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - frontend
      - backend
